### ISSUE TITLE
Write menu interface

### ISSUE THREAD

**Issue by BlackSpirit96** [BlackSpirit96/not_simple_chess#1]
Menu example:
* Start game
* Load game
* Options
* Stats
* Achievements
* Exit

**Comment by ChameleonShroop** [comment]
How are we gonna do it? Graphical or text-line?

**Comment by ChameleonShroop** [comment]
How are we gonna make it? Graphical or text-line?

**Comment by BlackSpirit96** [comment]
Interface, with buttons, checkboxes, etc

**Comment by BlackSpirit96** [comment]
Update dynamic menu with the new buttons

**Comment by BlackSpirit96** [comment]
I did that, also with dynamic menu we can do every menu :3

**Comment by BlackSpirit96** [comment]
We should focus more on app engine where all the menus will be held
